org.joget.marketplace.DatalistBinderWrapper.title=Load Binder Wrapper
org.joget.marketplace.DatalistBinderWrapper.listBinder=Select Original Source of Data
org.joget.marketplace.DatalistBinderWrapper.script=Script
org.joget.marketplace.DatalistBinderWrapper.script.desc=Enter script in Java to manipulate content returned by load binder above. Variable "data" and "columns" are injected.